### ISSUE TITLE
Adding a license 

### ISSUE THREAD

**Issue by devhuber** [dmikusa-pivotal/binding-tool#6]
Hi!

I just wondered whether you are planning to add a license to the project. 
I would want to use your tool at work and I might even try to contribute. But I am not allowed to because of some legal topics, since the repo does not contain a LICENSE. 

For example MIT (https://opensource.org/licenses/MIT) would be nice. 

Best regards!

**Comment by dmikusa-pivotal** [comment]
Sorry, I had just not gotten around to it. Apache 2 is the license I almost always use. I've PR'd that into the repo. Happy to have any contributions you might like to make.

**Comment by devhuber** [comment]
Thank you :)
